CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  mandarin_level VARCHAR(50) NOT NULL DEFAULT 'Beginner',
  password_hash VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS lesson (
  id INTEGER PRIMARY KEY A08iUTOINCREMENT,
  title VARCHAR(120) NOT NULL,
  category VARCHAR(80) NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS quiz_result (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  quiz_name VARCHAR(120) NOT NULL,
  score INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS support_message (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL,
  message TEXT NOT NULL
);
